drop table lugar_bd
drop table tienda_bd 	
drop table rol_bd
drop table permiso_rol 
drop table tipo_bd
drop table producto_tipo
drop table producto_bd
drop table diario_bd
drop table oferta_bd
drop table natural_bd
drop table juridico_bd
drop table tienda_cliente
drop table carnet_bd
drop table empleado_bd
drop table usuario_bd
drop table vacacion_bd
drop table asistencia_bd 
drop table horario_bd
drop table empleado_horario
drop table departamento_bd 
drop table telefono_bd
drop table banco_bd
drop table punto_bd
drop table cliente_punto
drop table presupuesto_bd
drop table tarjeta_bd
drop table cheque_bd
drop table efectivo_bd
drop table estatus_bd
drop table compra_bd
drop table compra_estatus
drop table presupuesto_producto_bd
drop table pago_bd
drop table ordenreposicion_bd
drop table orden_producto
drop table mediospago
drop table inventario
