Insert into lugar_bd(Luga_Nombre,Luga_Tipo,CF_luga_lugar) values
('Venezuela','Pais',Null),
('Amazonas','Estado',1),
('Anzoátegui','Estado',1),
('Apure','Estado',1),
('Aragua','Estado',1),
('Barinas','Estado',1),
('Bolívar','Estado',1),
('Carabobo','Estado',1),
('Cojedes','Estado',1),
('Delta Amacuro','Estado',1),
('Falcón','Estado',1),
('Guárico','Estado',1),
('Lara','Estado',1),
('Mérida','Estado',1),
('Miranda','Estado',1),
('Monagas','Estado',1),
('Nueva Esparta','Estado',1),
('Portuguesa','Estado',1),
('Sucre','Estado',1),
('Táchira','Estado',1),
('Trujillo','Estado',1),
('Vargas','Estado',1),
('Yaracuy','Estado',1),
('Zulia','Estado',1),
('Distrito Capital','Estado',1),
('Dependencias Federales','Estado',1),
('Alto Orinoco','Municipio',2),
('Atabapo','Municipio',2),
('Atures','Municipio',2),
('Autana','Municipio',2),
('Manapiare','Municipio',2),
('Maroa','Municipio',2),
('Río Negro','Municipio',2),
('Anaco','Municipio',3),
('Aragua','Municipio',3),
('Manuel Ezequiel Bruzual','Municipio',3),
('Diego Bautista Urbaneja','Municipio',3),
('Fernando Peñalver','Municipio',3),
('Francisco Del Carmen Carvajal','Municipio',3),
('General Sir Arthur McGregor','Municipio',3),
('Guanta','Municipio',3),
('Independencia','Municipio',3),
('José Gregorio Monagas','Municipio',3),
('Juan Antonio Sotillo','Municipio',3),
('Juan Manuel Cajigal','Municipio',3),
('Libertad','Municipio',3),
('Francisco de Miranda','Municipio',3),
('Pedro María Freites','Municipio',3),
('Píritu','Municipio',3),
('San José de Guanipa','Municipio',3),
('San Juan de Capistrano','Municipio',3),
('Santa Ana','Municipio',3),
('Simón Bolívar','Municipio',3),
('Simón Rodríguez','Municipio',3),
('Achaguas','Municipio',4),
('Biruaca','Municipio',4),
('Muñóz','Municipio',4),
('Páez','Municipio',4),
('Pedro Camejo','Municipio',4),
('Rómulo Gallegos','Municipio',4),
('San Fernando','Municipio',4),
('Atanasio Girardot','Municipio',5),
('Bolívar','Municipio',5),
('Camatagua','Municipio',5),
('Francisco Linares Alcántara','Municipio',5),
('José Ángel Lamas','Municipio',5),
('José Félix Ribas','Municipio',5),
('José Rafael Revenga','Municipio',5),
('Libertador','Municipio',5),
('Mario Briceño Iragorry','Municipio',5),
('Ocumare de la Costa de Oro','Municipio',5),
('San Casimiro','Municipio',5),
('San Sebastián','Municipio',5),
('Santiago Mariño','Municipio',5),
('Santos Michelena','Municipio',5),
('Sucre','Municipio',5),
('Tovar','Municipio',5),
('Urdaneta','Municipio',5),
('Zamora','Municipio',5),
('Alberto Arvelo Torrealba','Municipio',6),
('Andrés Eloy Blanco','Municipio',6),
('Antonio José de Sucre','Municipio',6),
('Arismendi','Municipio',6),
('Barinas','Municipio',6),
('Bolívar','Municipio',6),
('Cruz Paredes','Municipio',6),
('Ezequiel Zamora','Municipio',6),
('Obispos','Municipio',6),
('Pedraza','Municipio',6),
('Rojas','Municipio',6),
('Sosa','Municipio',6),
('Caroní','Municipio',7),
('Cedeño','Municipio',7),
('El Callao','Municipio',7),
('Gran Sabana','Municipio',7),
('Heres','Municipio',7),
('Piar','Municipio',7),
('Angostura (Raúl Leoni)','Municipio',7),
('Roscio','Municipio',7),
('Sifontes','Municipio',7),
('Sucre','Municipio',7),
('Padre Pedro Chien','Municipio',7),
('Bejuma','Municipio',8),
('Carlos Arvelo','Municipio',8),
('Diego Ibarra','Municipio',8),
('Guacara','Municipio',8),
('Juan José Mora','Municipio',8),
('Libertador','Municipio',8),
('Los Guayos','Municipio',8),
('Miranda','Municipio',8),
('Montalbán','Municipio',8),
('Naguanagua','Municipio',8),
('Puerto Cabello','Municipio',8),
('San Diego','Municipio',8),
('San Joaquín','Municipio',8),
('Valencia','Municipio',8),
('Anzoátegui','Municipio',9),
('Tinaquillo','Municipio',9),
('Girardot','Municipio',9),
('Lima Blanco','Municipio',9),
('Pao de San Juan Bautista','Municipio',9),
('Ricaurte','Municipio',9),
('Rómulo Gallegos','Municipio',9),
('San Carlos','Municipio',9),
('Tinaco','Municipio',9),
('Antonio Díaz','Municipio',10),
('Casacoima','Municipio',10),
('Pedernales','Municipio',10),
('Tucupita','Municipio',10),
('Acosta','Municipio',11),
('Bolívar','Municipio',11),
('Buchivacoa','Municipio',11),
('Cacique Manaure','Municipio',11),
('Carirubana','Municipio',11),
('Colina','Municipio',11),
('Dabajuro','Municipio',11),
('Democracia','Municipio',11),
('Falcón','Municipio',11),
('Federación','Municipio',11),
('Jacura','Municipio',11),
('José Laurencio Silva','Municipio',11),
('Los Taques','Municipio',11),
('Mauroa','Municipio',11),
('Miranda','Municipio',11),
('Monseñor Iturriza','Municipio',11),
('Palmasola','Municipio',11),
('Petit','Municipio',11),
('Píritu','Municipio',11),
('San Francisco','Municipio',11),
('Sucre','Municipio',11),
('Tocópero','Municipio',11),
('Unión','Municipio',11),
('Urumaco','Municipio',11),
('Zamora','Municipio',11),
('Camaguán','Municipio',12),
('Chaguaramas','Municipio',12),
('El Socorro','Municipio',12),
('José Félix Ribas','Municipio',12),
('José Tadeo Monagas','Municipio',12),
('Juan Germán Roscio','Municipio',12),
('Julián Mellado','Municipio',12),
('Las Mercedes','Municipio',12),
('Leonardo Infante','Municipio',12),
('Pedro Zaraza','Municipio',12),
('Ortíz','Municipio',12),
('San Gerónimo de Guayabal','Municipio',12),
('San José de Guaribe','Municipio',12),
('Santa María de Ipire','Municipio',12),
('Sebastián Francisco de Miranda','Municipio',12),
('Andrés Eloy Blanco','Municipio',13),
('Crespo','Municipio',13),
('Iribarren','Municipio',13),
('Jiménez','Municipio',13),
('Morán','Municipio',13),
('Palavecino','Municipio',13),
('Simón Planas','Municipio',3),
('Torres','Municipio',13),
('Urdaneta','Municipio',13),
('Alberto Adriani','Municipio',14),
('Andrés Bello','Municipio',14),
('Antonio Pinto Salinas','Municipio',14),
('Aricagua','Municipio',14),
('Arzobispo Chacón','Municipio',14),
('Campo Elías','Municipio',14),
('Caracciolo Parra Olmedo','Municipio',14),
('Cardenal Quintero','Municipio',14),
('Guaraque','Municipio',14),
('Julio César Salas','Municipio',14),
('Justo Briceño','Municipio',14),
('Libertador','Municipio',14),
('Miranda','Municipio',14),
('Obispo Ramos de Lora','Municipio',14),
('Padre Noguera','Municipio',14),
('Pueblo Llano','Municipio',14),
('Rangel','Municipio',14),
('Rivas Dávila','Municipio',14),
('Santos Marquina','Municipio',14),
('Sucre','Municipio',14),
('Tovar','Municipio',14),
('Tulio Febres Cordero','Municipio',14),
('Zea','Municipio',14),
('Acevedo','Municipio',15),
('Andrés Bello','Municipio',15),
('Baruta','Municipio',15),
('Brión','Municipio',15),
('Buroz','Municipio',15),
('Carrizal','Municipio',15),
('Chacao','Municipio',15),
('Cristóbal Rojas','Municipio',15),
('El Hatillo','Municipio',15),
('Guaicaipuro','Municipio',15),
('Independencia','Municipio',15),
('Lander','Municipio',15),
('Los Salias','Municipio',15),
('Páez','Municipio',15),
('Paz Castillo','Municipio',15),
('Pedro Gual','Municipio',15),
('Plaza','Municipio',15),
('Simón Bolívar','Municipio',15),
('Sucre','Municipio',15),
('Urdaneta','Municipio',15),
('Zamora','Municipio',15),
('Acosta','Municipio',16),
('Aguasay','Municipio',16),
('Bolívar','Municipio',16),
('Caripe','Municipio',16),
('Cedeño','Municipio',16),
('Ezequiel Zamora','Municipio',16),
('Libertador','Municipio',16),
('Maturín','Municipio',16),
('Piar','Municipio',16),
('Punceres','Municipio',16),
('Santa Bárbara','Municipio',16),
('Sotillo','Municipio',16),
('Uracoa','Municipio',16),
('Antolín del Campo','Municipio',17),
('Arismendi','Municipio',17),
('García','Municipio',17),
('Gómez','Municipio',17),
('Maneiro','Municipio',17),
('Marcano','Municipio',17),
('Mariño','Municipio',17),
('Península de Macanao','Municipio',17),
('Tubores','Municipio',17),
('Villalba','Municipio',17),
('Díaz','Municipio',17),
('Agua Blanca','Municipio',18),
('Araure','Municipio',18),
('Esteller','Municipio',18),
('Guanare','Municipio',18),
('Guanarito','Municipio',18),
('Monseñor José Vicente de Unda','Municipio',18),
('Ospino','Municipio',18),
('Páez','Municipio',18),
('Papelón','Municipio',18),
('San Genaro de Boconoíto','Municipio',18),
('San Rafael de Onoto','Municipio',18),
('Santa Rosalía','Municipio',18),
('Sucre','Municipio',18),
('Turén','Municipio',18),
('Andrés Eloy Blanco','Municipio',19),
('Andrés Mata','Municipio',19),
('Arismendi','Municipio',19),
('Benítez','Municipio',19),
('Bermúdez','Municipio',19),
('Bolívar','Municipio',19),
('Cajigal','Municipio',19),
('Cruz Salmerón Acosta','Municipio',19),
('Libertador','Municipio',19),
('Mariño','Municipio',19),
('Mejía','Municipio',19),
('Montes','Municipio',19),
('Ribero','Municipio',19),
('Sucre','Municipio',19),
('Valdéz','Municipio',19),
('Andrés Bello','Municipio',20),
('Antonio Rómulo Costa','Municipio',20),
('Ayacucho','Municipio',20),
('Bolívar','Municipio',20),
('Cárdenas','Municipio',20),
('Córdoba','Municipio',20),
('Fernández Feo','Municipio',20),
('Francisco de Miranda','Municipio',20),
('García de Hevia','Municipio',20),
('Guásimos','Municipio',20),
('Independencia','Municipio',20),
('Jáuregui','Municipio',20),
('José María Vargas','Municipio',20),
('Junín','Municipio',20),
('Libertad','Municipio',20),
('Libertador','Municipio',20),
('Lobatera','Municipio',20),
('Michelena','Municipio',20),
('Panamericano','Municipio',20),
('Pedro María Ureña','Municipio',20),
('Rafael Urdaneta','Municipio',20),
('Samuel Darío Maldonado','Municipio',20),
('San Cristóbal','Municipio',20),
('Seboruco','Municipio',20),
('Simón Rodríguez','Municipio',20),
('Sucre','Municipio',20),
('Torbes','Municipio',20),
('Uribante','Municipio',20),
('San Judas Tadeo','Municipio',20),
('Andrés Bello','Municipio',21),
('Boconó','Municipio',21),
('Bolívar','Municipio',21),
('Candelaria','Municipio',21),
('Carache','Municipio',21),
('Escuque','Municipio',21),
('José Felipe Márquez Cañizalez','Municipio',21),
('Juan Vicente Campos Elías','Municipio',21),
('La Ceiba','Municipio',21),
('Miranda','Municipio',21),
('Monte Carmelo','Municipio',21),
('Motatán','Municipio',21),
('Pampán','Municipio',21),
('Pampanito','Municipio',21),
('Rafael Rangel','Municipio',21),
('San Rafael de Carvajal','Municipio',21),
('Sucre','Municipio',21),
('Trujillo','Municipio',21),
('Urdaneta','Municipio',21),
('Valera','Municipio',21),
('Vargas','Municipio',22),
('Arístides Bastidas','Municipio',23),
('Bolívar','Municipio',23),
('Bruzual','Municipio',23),
('Cocorote','Municipio',23),
('Independencia','Municipio',23),
('José Antonio Páez','Municipio',23),
('La Trinidad','Municipio',23),
('Manuel Monge','Municipio',23),
('Nirgua','Municipio',23),
('Peña','Municipio',23),
('San Felipe','Municipio',23),
('Sucre','Municipio',23),
('Urachiche','Municipio',23),
('José Joaquín Veroes','Municipio',23),
('Almirante Padilla','Municipio',24),
('Baralt','Municipio',24),
('Cabimas','Municipio',24),
('Catatumbo','Municipio',24),
('Colón','Municipio',24),
('Francisco Javier Pulgar','Municipio',24),
('Páez','Municipio',24),
('Jesús Enrique Losada','Municipio',24),
('Jesús María Semprún','Municipio',24),
('La Cañada de Urdaneta','Municipio',24),
('Lagunillas','Municipio',24),
('Machiques de Perijá','Municipio',24),
('Mara','Municipio',24),
('Maracaibo','Municipio',24),
('Miranda','Municipio',24),
('Rosario de Perijá','Municipio',24),
('San Francisco','Municipio',24),
('Santa Rita','Municipio',24),
('Simón Bolívar','Municipio',24),
('Sucre','Municipio',24),
('Valmore Rodríguez','Municipio',24),
('Libertador','Municipio',25),
('Alto Orinoco','Parroquia',27),
('HuachamacareAcanaña','Parroquia',27),
('MarawakaTokyShamanaña','Parroquia',27),
('MavakaMavaka','Parroquia',27),
('Sierra Parima Parimabé','Parroquia',27),
('Ucata Laja Lisa','Parroquia',28),
('YapacanaMacuruco','Parroquia',28),
('CanameGuarinuma','Parroquia',28),
('Fernando Girón Tovar','Parroquia',29),
('Luis Alberto Gómez','Parroquia',29),
('Pahueña Limón de Parhueña','Parroquia',29),
('PlatanillalPlatanillal','Parroquia',29),
('Samariapo','Parroquia',30),
('Sipapo','Parroquia',30),
('Munduapo','Parroquia',30),
('Guayapo','Parroquia',30),
('Alto Ventuari','Parroquia',31),
('Medio Ventuari','Parroquia',31),
('Bajo Ventuari','Parroquia',31),
('Victorino','Parroquia',32),
('Comunidad','Parroquia',32),
('Casiquiare','Parroquia',33),
('Cocuy','Parroquia',33),
('San Carlos de Río Negro','Parroquia',33),
('Solano','Parroquia',33),
('Anaco','Parroquia',34),
('San Joaquín','Parroquia',34),
('Cachipo','Parroquia',35),
('Aragua de Barcelona','Parroquia',35),
('Lechería','Parroquia',37),
('El Morro','Parroquia',37),
('Puerto Píritu','Parroquia',38),
('San Miguel','Parroquia',38),
('Sucre','Parroquia',38),
('Valle de Guanape','Parroquia',39),
('Santa Bárbara','Parroquia',39),
('El Chaparro','Parroquia',40),
('Tomás Alfaro','Parroquia',40),
('Calatrava','Parroquia',40),
('Guanta','Parroquia',41),
('Chorrerón','Parroquia',41),
('Mamo','Parroquia',42),
('Soledad','Parroquia',42),
('Mapire','Parroquia',43),
('Piar','Parroquia',43),
('Santa Clara','Parroquia',43),
('San Diego de Cabrutica','Parroquia',43),
('Uverito','Parroquia',43),
('Zuata','Parroquia',43),
('Puerto La Cruz','Parroquia',44),
('Pozuelos','Parroquia',44),
('Onoto','Parroquia',45),
('San Pablo','Parroquia',45),
('San Mateo','Parroquia',46),
('El Carito','Parroquia',46),
('Santa Inés','Parroquia',46),
('La Romereña','Parroquia',46),
('Atapirire','Parroquia',47),
('Boca del Pao','Parroquia',47),
('El Pao','Parroquia',47),
('Pariaguán','Parroquia',47),
('Cantaura','Parroquia',48),
('Libertador','Parroquia',48),
('Santa Rosa','Parroquia',48),
('Urica','Parroquia',48),
('Píritu','Parroquia',49),
('San Francisco','Parroquia',49),
('San José de Guanipa','Parroquia',50),
('Boca de Uchire','Parroquia',51),
('Boca de Chávez','Parroquia',51),
('Pueblo Nuevo','Parroquia',52),
('Santa Ana','Parroquia',52),
('Bergantín','Parroquia',53),
('Caigua','Parroquia',53),
('El Carmen','Parroquia',53),
('El Pilar','Parroquia',53),
('Naricual','Parroquia',53),
('San Crsitóbal','Parroquia',53),
('Edmundo Barrios','Parroquia',54),
('Miguel Otero Silva','Parroquia',54),
('Achaguas','Parroquia',55),
('Apurito','Parroquia',55),
('El Yagual','Parroquia',55),
('Guachara','Parroquia',55),
('Mucuritas','Parroquia',55),
('Queseras del medio','Parroquia',55),
('Biruaca','Parroquia',56),
('Bruzual','Parroquia',57),
('Mantecal','Parroquia',57),
('Quintero','Parroquia',57),
('Rincón Hondo','Parroquia',57),
('San Vicente','Parroquia',57),
('Guasdualito','Parroquia',58),
('Aramendi','Parroquia',58),
('El Amparo','Parroquia',58),
('San Camilo','Parroquia',58),
('Urdaneta','Parroquia',58),
('San Juan de Payara','Parroquia',59),
('Codazzi','Parroquia',59),
('Cunaviche','Parroquia',59),
('Elorza','Parroquia',60),
('La Trinidad','Parroquia',60),
('San Fernando','Parroquia',61),
('El Recreo','Parroquia',61),
('Peñalver','Parroquia',61),
('San Rafael de Atamaica','Parroquia',61),
('Pedro José Ovalles','Parroquia',62),
('Joaquín Crespo','Parroquia',62),
('José Casanova Godoy','Parroquia',62),
('Madre María de San José','Parroquia',62),
('Andrés Eloy Blanco','Parroquia',62),
('Los Tacarigua','Parroquia',62),
('Las Delicias','Parroquia',62),
('Choroní','Parroquia',62),
('Bolívar','Parroquia',63),
('Camatagua','Parroquia',64),
('Carmen de Cura','Parroquia',64),
('Santa Rita','Parroquia',65),
('Francisco de Miranda','Parroquia',65),
('Moseñor Feliciano González','Parroquia',65),
('Santa Cruz','Parroquia',66),
('José Félix Ribas','Parroquia',67),
('Castor Nieves Ríos','Parroquia',67),
('Las Guacamayas','Parroquia',67),
('Pao de Zárate','Parroquia',67),
('Zuata','Parroquia',67),
('José Rafael Revenga','Parroquia',68),
('Palo Negro','Parroquia',69),
('San Martín de Porres','Parroquia',69),
('El Limón','Parroquia',70),
('Caña de Azúcar','Parroquia',70),
('Ocumare de la Costa','Parroquia',71),
('San Casimiro','Parroquia',72),
('Güiripa','Parroquia',72),
('Ollas de Caramacate','Parroquia',72),
('Valle Morín','Parroquia',72),
('San Sebastían','Parroquia',73),
('Turmero','Parroquia',74),
('Arevalo Aponte','Parroquia',74),
('Chuao','Parroquia',74),
('Samán de Güere','Parroquia',74),
('Alfredo Pacheco Miranda','Parroquia',74),
('Santos Michelena','Parroquia',75),
('Tiara','Parroquia',75),
('Cagua','Parroquia',76),
('Bella Vista','Parroquia',76),
('Tovar','Parroquia',77),
('Urdaneta','Parroquia',78),
('Las Peñitas','Parroquia',78),
('San Francisco de Cara','Parroquia',78),
('Taguay','Parroquia',78),
('Zamora','Parroquia',79),
('Magdaleno','Parroquia',79),
('San Francisco de Asís','Parroquia',79),
('Valles de Tucutunemo','Parroquia',79),
('Augusto Mijares','Parroquia',79),
('Sabaneta','Parroquia',80),
('Juan Antonio Rodríguez Domínguez','Parroquia',80),
('El Cantón','Parroquia',81),
('Santa Cruz de Guacas','Parroquia',81),
('Puerto Vivas','Parroquia',81),
('Ticoporo','Parroquia',82),
('Nicolás Pulido','Parroquia',82),
('Andrés Bello','Parroquia',82),
('Arismendi','Parroquia',83),
('Guadarrama','Parroquia',83),
('La Unión','Parroquia',83),
('San Antonio','Parroquia',83),
('Barinas','Parroquia',84),
('Alberto Arvelo Larriva','Parroquia',84),
('San Silvestre','Parroquia',84),
('Santa Inés','Parroquia',84),
('Santa Lucía','Parroquia',84),
('Torumos','Parroquia',84),
('El Carmen','Parroquia',84),
('Rómulo Betancourt','Parroquia',84),
('Corazón de Jesús','Parroquia',84),
('Ramón Ignacio Méndez','Parroquia',84),
('Alto Barinas','Parroquia',84),
('Manuel Palacio Fajardo','Parroquia',84),
('Juan Antonio Rodríguez Domínguez','Parroquia',84),
('Dominga Ortiz de Páez','Parroquia',84),
('Barinitas','Parroquia',85),
('Altamira de Cáceres','Parroquia',85),
('Calderas','Parroquia',85),
('Barrancas','Parroquia',86),
('El Socorro','Parroquia',86),
('Mazparrito','Parroquia',86),
('Santa Bárbara','Parroquia',86),
('Pedro Briceño Méndez','Parroquia',87),
('Ramón Ignacio Méndez','Parroquia',87),
('José Ignacio del Pumar','Parroquia',87),
('Obispos','Parroquia',88),
('Guasimitos','Parroquia',88),
('El Real','Parroquia',88),
('La Luz','Parroquia',88),
('Ciudad Bolívia','Parroquia',89),
('José Ignacio Briceño','Parroquia',89),
('José Félix Ribas','Parroquia',89),
('Páez','Parroquia',89),
('Libertad','Parroquia',90),
('Dolores','Parroquia',90),
('Santa Rosa','Parroquia',90),
('Palacio Fajardo','Parroquia',90),
('Ciudad de Nutrias','Parroquia',91),
('El Regalo','Parroquia',91),
('Puerto Nutrias','Parroquia',91),
('Santa Catalina','Parroquia',91),
('Cachamay','Parroquia',92),
('Chirica','Parroquia',92),
('Dalla Costa','Parroquia',92),
('Once de Abril','Parroquia',92),
('Simón Bolívar','Parroquia',92),
('Unare','Parroquia',92),
('Universidad','Parroquia',92),
('Vista al Sol','Parroquia',92),
('Pozo Verde','Parroquia',92),
('Yocoima','Parroquia',92),
('5 de Julio','Parroquia',92),
('Cedeño','Parroquia',93),
('Altagracia','Parroquia',93),
('Ascensión Farreras','Parroquia',93),
('Guaniamo','Parroquia',93),
('La Urbana','Parroquia',93),
('Pijiguaos','Parroquia',93),
('El Callao','Parroquia',94),
('Gran Sabana','Parroquia',95),
('Ikabarú','Parroquia',95),
('Catedral','Parroquia',96),
('Zea','Parroquia',96),
('Orinoco','Parroquia',96),
('José Antonio Páez','Parroquia',96),
('Marhuanta','Parroquia',96),
('Agua Salada','Parroquia',96),
('Vista Hermosa','Parroquia',96),
('La Sabanita','Parroquia',96),
('Panapana','Parroquia',96),
('Andrés Eloy Blanco','Parroquia',97),
('Pedro Cova','Parroquia',97),
('Raúl Leoni','Parroquia',98),
('Barceloneta','Parroquia',98),
('Santa Bárbara','Parroquia',98),
('San Francisco','Parroquia',98),
('Roscio','Parroquia',99),
('Salóm','Parroquia',99),
('Sifontes','Parroquia',100),
('Dalla Costa','Parroquia',100),
('San Isidro','Parroquia',100),
('Sucre','Parroquia',101),
('Aripao','Parroquia',101),
('Guarataro','Parroquia',101),
('Las Majadas','Parroquia',101),
('Moitaco','Parroquia',101),
('Padre Pedro Chien','Parroquia',102),
('Río Grande','Parroquia',102),
('Bejuma','Parroquia',103),
('Canoabo','Parroquia',103),
('Simón Bolívar','Parroquia',103),
('Güigüe','Parroquia',104),
('Carabobo','Parroquia',104),
('Tacarigua','Parroquia',104),
('Mariara','Parroquia',105),
('Aguas Calientes','Parroquia',105),
('Ciudad Alianza','Parroquia',106),
('Guacara','Parroquia',106),
('Yagua','Parroquia',106),
('Morón','Parroquia',107),
('Yagua','Parroquia',107),
('Tocuyito','Parroquia',108),
('Independencia','Parroquia',108),
('Los Guayos','Parroquia',109),
('Miranda','Parroquia',110),
('Montalbán','Parroquia',111),
('Naguanagua','Parroquia',112),
('Bartolomé Salóm','Parroquia',113),
('Democracia','Parroquia',113),
('Fraternidad','Parroquia',113),
('Goaigoaza','Parroquia',113),
('Juan José Flores','Parroquia',113),
('Unión','Parroquia',113),
('Borburata','Parroquia',113),
('Patanemo','Parroquia',113),
('San Diego','Parroquia',114),
('San Joaquín','Parroquia',115),
('Candelaria','Parroquia',116),
('Catedral','Parroquia',116),
('El Socorro','Parroquia',116),
('Miguel Peña','Parroquia',116),
('Rafael Urdaneta','Parroquia',116),
('San Blas','Parroquia',116),
('San José','Parroquia',116),
('Santa Rosa','Parroquia',116),
('Negro Primero','Parroquia',116),
('Cojedes','Parroquia',117),
('Juan de Mata Suárez','Parroquia',117),
('Tinaquillo','Parroquia',118),
('El Baúl','Parroquia',119),
('Sucre','Parroquia',119),
('La Aguadita','Parroquia',120),
('Macapo','Parroquia',120),
('El Pao','Parroquia',121),
('El Amparo','Parroquia',122),
('Libertad de Cojedes','Parroquia',122),
('Rómulo Gallegos','Parroquia',123),
('San Carlos de Austria','Parroquia',124),
('Juan Ángel Bravo','Parroquia',124),
('Manuel Manrique','Parroquia',124),
('General en Jefe José Laurencio Silva','Parroquia',125),
('Curiapo','Parroquia',126),
('Almirante Luis Brión','Parroquia',126),
('Francisco Aniceto Lugo','Parroquia',126),
('Manuel Renaud','Parroquia',126),
('Padre Barral','Parroquia',126),
('Santos de Abelgas','Parroquia',126),
('Imataca','Parroquia',127),
('Cinco de Julio','Parroquia',127),
('Juan Bautista Arismendi','Parroquia',127),
('Manuel Piar','Parroquia',127),
('Rómulo Gallegos','Parroquia',127),
('Pedernales','Parroquia',128),
('Luis Beltrán Prieto Figueroa','Parroquia',128),
('San José (Delta Amacuro)','Parroquia',129),
('José Vidal Marcano','Parroquia',129),
('Juan Millán','Parroquia',129),
('Leonardo Ruíz Pineda','Parroquia',129),
('Mariscal Antonio José de Sucre','Parroquia',129),
('Monseñor Argimiro García','Parroquia',129),
('San Rafael (Delta Amacuro)','Parroquia',129),
('Virgen del Valle','Parroquia',129),
('Clarines','Parroquia',36),
('Guanape','Parroquia',36),
('Sabana de Uchire','Parroquia',36),
('Capadare','Parroquia',130),
('La Pastora','Parroquia',130),
('Libertador','Parroquia',130),
('San Juan de los Cayos','Parroquia',130),
('Aracua','Parroquia',131),
('La Peña','Parroquia',131), 
('San Luis','Parroquia',131),
('Bariro','Parroquia',132),
('Borojó','Parroquia',132),
('Capatárida','Parroquia',132),
('Guajiro','Parroquia',132),
('Seque','Parroquia',132),
('Zazárida','Parroquia',132),
('Valle de Eroa','Parroquia',132),
('Cacique Manaure','Parroquia',133),
('Norte','Parroquia',134),
('Carirubana','Parroquia',134),
('Santa Ana','Parroquia',134),
('Urbana Punta Cardón','Parroquia',134),
('La Vela de Coro','Parroquia',135),
('Acurigua','Parroquia',135),
('Guaibacoa','Parroquia',135),
('Las Calderas','Parroquia',135),
('Macoruca','Parroquia',135),
('Dabajuro','Parroquia',136),
('Agua Clara','Parroquia',137),
('Avaria','Parroquia',137),
('Pedregal','Parroquia',137),
('Piedra Grande','Parroquia',137),
('Purureche','Parroquia',137),
('Adaure','Parroquia',138),
('Adícora','Parroquia',138),
('Baraived','Parroquia',138),
('Buena Vista','Parroquia',138),
('Jadacaquiva','Parroquia',138),
('El Vínculo','Parroquia',138),
('El Hato','Parroquia',138),
('Moruy','Parroquia',138),
('Pueblo Nuevo','Parroquia',138),
('Agua Larga','Parroquia',139),
('El Paují','Parroquia',139),
('Independencia','Parroquia',13),
('Mapararí','Parroquia',139),
('Agua Linda','Parroquia',140),
('Araurima','Parroquia',140),
('Jacura','Parroquia',140),
('Tucacas','Parroquia',141),
('Boca de Aroa','Parroquia',141),
('Los Taques','Parroquia',142),
('Judibana','Parroquia',142),
('Mene de Mauroa','Parroquia',143),
('San Félix','Parroquia',143),
('Casigua','Parroquia',143),
('Guzmán Guillermo','Parroquia',144),
('Mitare','Parroquia',144),
('Río Seco','Parroquia',144),
('Sabaneta','Parroquia',144),
('San Antonio','Parroquia',144),
('San Gabriel','Parroquia',144),
('Santa Ana','Parroquia',144),
('Boca del Tocuyo','Parroquia',145),
('Chichiriviche','Parroquia',145),
('Tocuyo de la Costa','Parroquia',145),
('Palmasola','Parroquia',146),
('Cabure','Parroquia',147),
('Colina','Parroquia',147),
('Curimagua','Parroquia',147),
('San José de la Costa','Parroquia',148),
('Píritu','Parroquia',148),
('San Francisco','Parroquia',149),
('Sucre','Parroquia',150),
('Pecaya','Parroquia',150),
('Tocópero','Parroquia',151),
('El Charal','Parroquia',152),
('Las Vegas del Tuy','Parroquia',152),
('Santa Cruz de Bucaral','Parroquia',152),
('Bruzual','Parroquia',153),
('Urumaco','Parroquia',153),
('Puerto Cumarebo','Parroquia',154),
('La Ciénaga','Parroquia',154),
('La Soledad','Parroquia',154),
('Pueblo Cumarebo','Parroquia',154),
('Zazárida','Parroquia',154),
('Churuguara','Parroquia',139),
('Camaguán','Parroquia',155),
('Puerto Miranda','Parroquia',155),
('Uverito','Parroquia',155),
('Chaguaramas','Parroquia',156),
('El Socorro','Parroquia',157),
('Tucupido','Parroquia',158),
('San Rafael de Laya','Parroquia',158),
('Altagracia de Orituco','Parroquia',159),
('San Rafael de Orituco','Parroquia',159),
('San Francisco Javier de Lezama','Parroquia',159),
('Paso Real de Macaira','Parroquia',159),
('Carlos Soublette','Parroquia',159),
('San Francisco de Macaira','Parroquia',159),
('Libertad de Orituco','Parroquia',159),
('Cantaclaro','Parroquia',160),
('San Juan de los Morros','Parroquia',160),
('Parapara','Parroquia',160),
('El Sombrero','Parroquia',161),
('Sosa','Parroquia',161),
('Las Mercedes','Parroquia',162),
('Cabruta','Parroquia',162),
('Santa Rita de Manapire','Parroquia',162),
('Valle de la Pascua','Parroquia',163),
('Espino','Parroquia',163),
('San José de Unare','Parroquia',164),
('Zaraza','Parroquia',164),
('San José de Tiznados','Parroquia',165),
('San Francisco de Tiznados','Parroquia',165),
('San Lorenzo de Tiznados','Parroquia',165),
('Ortiz','Parroquia',165),
('Guayabal','Parroquia',166),
('Cazorla','Parroquia',166),
('San José de Guaribe','Parroquia',167),
('Uveral','Parroquia',167),
('Santa María de Ipire','Parroquia',168),
('Altamira','Parroquia',168),
('El Calvario','Parroquia',169),
('El Rastro','Parroquia',169),
('Guardatinajas','Parroquia',169),
('Capital Urbana Calabozo','Parroquia',169),
('Quebrada Honda de Guache','Parroquia',170),
('Pío Tamayo','Parroquia',170),
('Yacambú','Parroquia',170),
('Fréitez','Parroquia',171),
('José María Blanco','Parroquia',171),
('Catedral','Parroquia',172),
('Concepción','Parroquia',172),
('El Cují','Parroquia',172),
('Juan de Villegas','Parroquia',172),
('Santa Rosa','Parroquia',172),
('Tamaca','Parroquia',172),
('Unión','Parroquia',172),
('Aguedo Felipe Alvarado','Parroquia',172),
('Buena Vista','Parroquia',172),
('Juárez','Parroquia',172),
('Juan Bautista Rodríguez','Parroquia',173),
('Cuara','Parroquia',173),
('Diego de Lozada','Parroquia',173),
('Paraíso de San José','Parroquia',173),
('San Miguel','Parroquia',173),
('Tintorero','Parroquia',173),
('José Bernardo Dorante','Parroquia',173),
('Coronel Mariano Peraza','Parroquia',173),
('Bolívar','Parroquia',174),
('Anzoátegui','Parroquia',174),
('Guarico','Parroquia',174),
('Hilario Luna y Luna','Parroquia',174),
('Humocaro Alto','Parroquia',174),
('Humocaro Bajo','Parroquia',174),
('La Candelaria','Parroquia',174),
('Morán','Parroquia',174),
('Cabudare','Parroquia',175),
('José Gregorio Bastidas','Parroquia',175),
('Agua Viva','Parroquia',175),
('Sarare','Parroquia',176),
('Buría','Parroquia',176),
('Gustavo Vegas León','Parroquia',176),
('Trinidad Samuel','Parroquia',177),
('Antonio Díaz','Parroquia',177),
('Camacaro','Parroquia',177),
('Castañeda','Parroquia',177),
('Cecilio Zubillaga','Parroquia',177),
('Chiquinquirá','Parroquia',177),
('El Blanco','Parroquia',177),
('Espinoza de los Monteros','Parroquia',177),
('Lara','Parroquia',177),
('Las Mercedes','Parroquia',177),
('Manuel Morillo','Parroquia',177),
('Montaña Verde','Parroquia',177),
('Montes de Oca','Parroquia',177),
('Torres','Parroquia',177),
('Heriberto Arroyo','Parroquia',177),
('Reyes Vargas','Parroquia',177),
('Altagracia','Parroquia',177),
('Siquisique','Parroquia',178),
('Moroturo','Parroquia',178),
('San Miguel','Parroquia',178),
('Xaguas','Parroquia',178),
('Presidente Betancourt','Parroquia',179),
('Presidente Páez','Parroquia',179),
('Presidente Rómulo Gallegos','Parroquia',179),
('Gabriel Picón González','Parroquia',179),
('Héctor Amable Mora','Parroquia',179),
('José NuceteSardi','Parroquia',179),
('Pulido Méndez','Parroquia',179),
('La Azulita','Parroquia',180),
('Santa Cruz de Mora','Parroquia',181),
('Mesa Bolívar','Parroquia',181),
('Mesa de Las Palmas','Parroquia',181),
('Aricagua','Parroquia',182),
('San Antonio','Parroquia',182),
('Canagua','Parroquia',183),
('Capurí','Parroquia',183),
('Chacantá','Parroquia',183),
('El Molino','Parroquia',183),
('Guaimaral','Parroquia',183),
('Mucutuy','Parroquia',183),
('Mucuchachí','Parroquia',183),
('Fernández Peña','Parroquia',184),
('Matriz','Parroquia',184),
('Montalbán','Parroquia',184),
('Acequias','Parroquia',184),
('Jají','Parroquia',184),
('La Mesa','Parroquia',184),
('San José del Sur','Parroquia',184),
('Tucaní','Parroquia',185),
('Florencio Ramírez','Parroquia',185),
('Santo Domingo','Parroquia',186),
('Las Piedras','Parroquia',186),
('Guaraque','Parroquia',187),
('Mesa de Quintero','Parroquia',187),
('Río Negro','Parroquia',187),
('Arapuey','Parroquia',188),
('Palmira','Parroquia',188),
('San Cristóbal de Torondoy','Parroquia',189),
('Torondoy','Parroquia',189),
('Antonio Spinetti Dini','Parroquia',190),
('Arias','Parroquia',190),
('Caracciolo Parra Pérez','Parroquia',190),
('Domingo Peña','Parroquia',190),
('El Llano','Parroquia',190),
('Gonzalo Picón Febres','Parroquia',190),
('Jacinto Plaza','Parroquia',190),
('Juan Rodríguez Suárez','Parroquia',190),
('Lasso de la Vega','Parroquia',190),
('Mariano Picón Salas','Parroquia',190),
('Milla','Parroquia',190),
('Osuna Rodríguez','Parroquia',190),
('Sagrario','Parroquia',190),
('El Morro','Parroquia',190),
('Los Nevados','Parroquia',190),
('Andrés Eloy Blanco','Parroquia',191),
('La Venta','Parroquia',191),
('Piñango','Parroquia',191),
('Timotes','Parroquia',191),
('Eloy Paredes','Parroquia',192),
('San Rafael de Alcázar','Parroquia',192),
('Santa Elena de Arenales','Parroquia',192),
('Santa María de Caparo','Parroquia',193),
('Pueblo Llano','Parroquia',194),
('Cacute','Parroquia',195),
('La Toma','Parroquia',195),
('Mucuchíes','Parroquia',195),
('Mucurubá','Parroquia',195),
('San Rafael','Parroquia',195),
('Gerónimo Maldonado','Parroquia',196),
('Bailadores','Parroquia',196),
('Tabay','Parroquia',197),
('Chiguará','Parroquia',198),
('Estánquez','Parroquia',198),
('Lagunillas','Parroquia',198),
('La Trampa','Parroquia',198),
('Pueblo Nuevo del Sur','Parroquia',198),
('San Juan','Parroquia',198),
('El Amparo','Parroquia',199),
('El Llano','Parroquia',199),
('San Francisco','Parroquia',199),
('Tovar','Parroquia',199),
('Independencia','Parroquia',200),
('María de la Concepción Palacios Blanco','Parroquia',200),
('Nueva Bolivia','Parroquia',200),
('Santa Apolonia','Parroquia',200),
('Caño El Tigre','Parroquia',201),
('Zea','Parroquia',201),
('Aragüita','Parroquia',202),
('Arévalo González','Parroquia',202),
('Capaya','Parroquia',202),
('Caucagua','Parroquia',202),
('Panaquire','Parroquia',202),
('Ribas','Parroquia',202),
('El Café','Parroquia',202),
('Marizapa','Parroquia',202),
('Cumbo','Parroquia',203),
('San José de Barlovento','Parroquia',203),
('El Cafetal','Parroquia',204),
('Las Minas','Parroquia',204),
('Nuestra Señora del Rosario','Parroquia',204),
('Higuerote','Parroquia',205),
('Curiepe','Parroquia',205),
('Tacarigua de Brión','Parroquia',205),
('Mamporal','Parroquia',206),
('Carrizal','Parroquia',207),
('Chacao','Parroquia',208),
('Charallave','Parroquia',209),
('Las Brisas','Parroquia',209),
('El Hatillo','Parroquia',210),
('Altagracia de la Montaña','Parroquia',211),
('Cecilio Acosta','Parroquia',211),
('Los Teques','Parroquia',211),
('El Jarillo','Parroquia',211),
('San Pedro','Parroquia',211),
('Tácata','Parroquia',211),
('Paracotos','Parroquia',211),
('Cartanal','Parroquia',212),
('Santa Teresa del Tuy','Parroquia',212),
('La Democracia','Parroquia',213),
('Ocumare del Tuy','Parroquia',213),
('Santa Bárbara','Parroquia',213),
('San Antonio de los Altos','Parroquia',214),
('Río Chico','Parroquia',215),
('El Guapo','Parroquia',215),
('Tacarigua de la Laguna','Parroquia',215),
('Paparo','Parroquia',215),
('San Fernando del Guapo','Parroquia',215),
('Santa Lucía del Tuy','Parroquia',216),
('Cúpira','Parroquia',217),
('Machurucuto','Parroquia',217),
('Guarenas','Parroquia',218),
('San Antonio de Yare','Parroquia',219),
('San Francisco de Yare','Parroquia',219),
('Leoncio Martínez','Parroquia',220),
('Petare','Parroquia',220),
('Caucagüita','Parroquia',220),
('Filas de Mariche','Parroquia',220),
('La Dolorita','Parroquia',220),
('Cúa','Parroquia',221),
('Nueva Cúa','Parroquia',221),
('Guatire','Parroquia',222),
('Bolívar','Parroquia',222),
('San Antonio de Maturín','Parroquia',223),
('San Francisco de Maturín','Parroquia',223),
('Aguasay','Parroquia',224),
('Caripito','Parroquia',225),
('El Guácharo','Parroquia',226),
('La Guanota','Parroquia',226),
('Sabana de Piedra','Parroquia',226),
('San Agustín','Parroquia',226),
('Teresen','Parroquia',226),
('Caripe','Parroquia',226),
('Areo','Parroquia',227),
('Capital Cedeño','Parroquia',227),
('San Félix de Cantalicio','Parroquia',227),
('Viento Fresco','Parroquia',227),
('El Tejero','Parroquia',228),
('Punta de Mata','Parroquia',228),
('Chaguaramas','Parroquia',229),
('Las Alhuacas','Parroquia',229),
('Tabasca','Parroquia',229),
('Temblador','Parroquia',229),
('Alto de los Godos','Parroquia',230),
('Boquerón','Parroquia',230),
('Las Cocuizas','Parroquia',230),
('La Cruz','Parroquia',230),
('San Simón','Parroquia',230),
('El Corozo','Parroquia',230),
('El Furrial','Parroquia',230),
('Jusepín','Parroquia',230),
('La Pica','Parroquia',230),
('San Vicente','Parroquia',230),
('Aparicio','Parroquia',231),
('Aragua de Maturín','Parroquia',231),
('Chaguamal','Parroquia',231),
('El Pinto','Parroquia',231),
('Guanaguana','Parroquia',231),
('La Toscana','Parroquia',231),
('Taguaya','Parroquia',231),
('Cachipo','Parroquia',232),
('Quiriquire','Parroquia',232),
('Santa Bárbara','Parroquia',233),
('Barrancas','Parroquia',234),
('Los Barrancos de Fajardo','Parroquia',234),
('Uracoa','Parroquia',235),
('Antolín del Campo','Parroquia',236),
('Arismendi','Parroquia',237),
('García','Parroquia',238),
('Francisco Fajardo','Parroquia',238),
('Bolívar','Parroquia',239),
('Guevara','Parroquia',239),
('Matasiete','Parroquia',239),
('Santa Ana','Parroquia',239),
('Sucre','Parroquia',239),
('Aguirre','Parroquia',240),
('Maneiro','Parroquia',240),
('Adrián','Parroquia',241),
('Juan Griego','Parroquia',241),
('Yaguaraparo','Parroquia',241),
('Porlamar','Parroquia',276),
('San Francisco de Macanao','Parroquia',277),
('Boca de Río','Parroquia',277),
('Tubores','Parroquia',278),
('Los Baleales','Parroquia',278),
('Vicente Fuentes','Parroquia',279),
('Villalba','Parroquia',279),
('San Juan Bautista','Parroquia',277),
('Zabala','Parroquia',280),
('Capital Araure','Parroquia',282),
('Río Acarigua','Parroquia',282),
('Capital Esteller','Parroquia',283),
('Uveral','Parroquia',283),
('Guanare','Parroquia',250),
('Córdoba','Parroquia',250),
('San José de la Montaña','Parroquia',250),
('San Juan de Guanaguanare','Parroquia',250),
('Virgen de la Coromoto','Parroquia',250),
('Guanarito','Parroquia',251),
('Trinidad de la Capilla','Parroquia',251),
('Divina Pastora','Parroquia',251),
('Monseñor José Vicente de Unda','Parroquia',252),
('Peña Blanca','Parroquia',252),
('Capital Ospino','Parroquia',253),
('Aparición','Parroquia',253),
('La Estación','Parroquia',253),
('Páez','Parroquia',254),
('Payara','Parroquia',254),
('Pimpinela','Parroquia',254),
('Ramón Peraza','Parroquia',254),
('Papelón','Parroquia',255),
('Caño Delgadito','Parroquia',255),
('San Genaro de Boconoito','Parroquia',256),
('Antolín Tovar','Parroquia',256),
('San Rafael de Onoto','Parroquia',257),
('Santa Fe','Parroquia',257),
('ThermoMorles','Parroquia',257),
('Santa Rosalía','Parroquia',258),
('Florida','Parroquia',258),
('Sucre','Parroquia',259),
('Concepción','Parroquia',259),
('San Rafael de Palo Alzado','Parroquia',259),
('Uvencio Antonio Velásquez','Parroquia',259),
('San José de Saguaz','Parroquia',259),
('Villa Rosa','Parroquia',259),
('Turén','Parroquia',260),
('Canelones','Parroquia',260),
('Santa Cruz','Parroquia',260),
('San Isidro Labrador','Parroquia',260),
('Mariño','Parroquia',261),
('Rómulo Gallegos','Parroquia',261),
('San José de Aerocuar','Parroquia',262),
('Tavera Acosta','Parroquia',262),
('Río Caribe','Parroquia',263),
('Antonio José de Sucre','Parroquia',263),
('El Morro de Puerto Santo','Parroquia',263),
('Puerto Santo','Parroquia',263),
('San Juan de las Galdonas','Parroquia',263),
('El Pilar','Parroquia',264),
('El Rincón','Parroquia',264),
('General Francisco Antonio Váquez','Parroquia',264),
('Guaraúnos','Parroquia',264),
('Tunapuicito','Parroquia',264),
('Unión','Parroquia',264),
('Santa Catalina','Parroquia',265),
('Santa Rosa','Parroquia',265),
('Santa Teresa','Parroquia',265),
('Bolívar','Parroquia',265),
('Maracapana','Parroquia',265),
('Libertad','Parroquia',267),
('El Paujil','Parroquia',267),
('Yaguaraparo','Parroquia',267),
('Cruz Salmerón Acosta','Parroquia',268),
('Chacopata','Parroquia',268),
('Manicuare','Parroquia',268),
('Tunapuy','Parroquia',269),
('Campo Elías','Parroquia',269),
('Irapa','Parroquia',270),
('Campo Claro','Parroquia',270),
('Maraval','Parroquia',270),
('San Antonio de Irapa','Parroquia',270),
('Soro','Parroquia',270),
('Mejía','Parroquia',271),
('Cumanacoa','Parroquia',272),
('Arenas','Parroquia',272),
('Aricagua','Parroquia',272),
('Cogollar','Parroquia',272),
('San Fernando','Parroquia',272),
('San Lorenzo','Parroquia',272),
('Villa Frontado (Muelle de Cariaco)','Parroquia',273),
('Catuaro','Parroquia',273),
('Rendón','Parroquia',273),
('San Cruz','Parroquia',273),
('Santa María','Parroquia',273),
('Altagracia','Parroquia',274),
('Santa Inés','Parroquia',274),
('Valentín Valiente','Parroquia',274),
('Ayacucho','Parroquia',274),
('San Juan','Parroquia',274),
('Raúl Leoni','Parroquia',274),
('Gran Mariscal','Parroquia',274),
('Cristóbal Colón','Parroquia',275),
('Bideau','Parroquia',275),
('Punta de Piedras','Parroquia',275),
('Güiria','Parroquia',275),
('Andrés Bello','Parroquia',276),
('Antonio Rómulo Costa','Parroquia',277),
('Ayacucho','Parroquia',278),
('Rivas Berti','Parroquia',278),
('San Pedro del Río','Parroquia',278),
('Bolívar','Parroquia',279),
('Palotal','Parroquia',279),
('General Juan Vicente Gómez','Parroquia',279),
('Isaías Medina Angarita','Parroquia',279),
('Cárdenas','Parroquia',280),
('Amenodoro Ángel Lamus','Parroquia',280),
('La Florida','Parroquia',280),
('Córdoba','Parroquia',281),
('Fernández Feo','Parroquia',282),
('Alberto Adriani','Parroquia',282),
('Santo Domingo','Parroquia',282),
('Francisco de Miranda','Parroquia',283),
('García de Hevia','Parroquia',284),
('Boca de Grita','Parroquia',284),
('José Antonio Páez','Parroquia',284),
('Guásimos','Parroquia',285),
('Independencia','Parroquia',286),
('Juan Germán Roscio','Parroquia',286),
('Román Cárdenas','Parroquia',286),
('Jáuregui','Parroquia',287),
('Emilio Constantino Guerrero','Parroquia',287),
('Monseñor Miguel Antonio Salas','Parroquia',287),
('José María Vargas','Parroquia',288),
('Junín','Parroquia',289),
('La Petrólea','Parroquia',289),
('Quinimarí','Parroquia',289),
('Bramón','Parroquia',289),
('Libertad','Parroquia',290),
('Cipriano Castro','Parroquia',290),
('Manuel Felipe Rugeles','Parroquia',290),
('Libertador','Parroquia',291),
('Doradas','Parroquia',291),
('Emeterio Ochoa','Parroquia',291),
('San Joaquín de Navay','Parroquia',291),
('Lobatera','Parroquia',292),
('Constitución','Parroquia',292),
('Michelena','Parroquia',293),
('Panamericano','Parroquia',294),
('La Palmita','Parroquia',294),
('Pedro María Ureña','Parroquia',295),
('Nueva Arcadia','Parroquia',295),
('Delicias','Parroquia',296),
('Pecaya','Parroquia',296),
('Samuel Darío Maldonado','Parroquia',297),
('Boconó','Parroquia',297),
('Hernández','Parroquia',297),
('La Concordia','Parroquia',298),
('San Juan Bautista','Parroquia',298),
('Pedro María Morantes','Parroquia',298),
('San Sebastián','Parroquia',298),
('Dr. Francisco Romero Lobo','Parroquia',298),
('Seboruco','Parroquia',299),
('Simón Rodríguez','Parroquia',300),
('Sucre','Parroquia',301),
('Eleazar López Contreras','Parroquia',301),
('San Pablo','Parroquia',301),
('Torbes','Parroquia',302),
('Uribante','Parroquia',303),
('Cárdenas','Parroquia',303),
('Juan Pablo Peñalosa','Parroquia',303),
('Potosí','Parroquia',303),
('San Judas Tadeo','Parroquia',304),
('Araguaney','Parroquia',305),
('El Jaguito','Parroquia',305),
('La Esperanza','Parroquia',305),
('Santa Isabel','Parroquia',305),
('Boconó','Parroquia',306),
('El Carmen','Parroquia',306),
('Mosquey','Parroquia',306),
('Ayacucho','Parroquia',306),
('Burbusay','Parroquia',306),
('General Ribas','Parroquia',306),
('Guaramacal','Parroquia',306),
('Vega de Guaramacal','Parroquia', 306),
('Monseñor Jáuregui','Parroquia',306),
('Rafael Rangel','Parroquia',306),
('San Miguel','Parroquia',306),
('San José','Parroquia',306),
('Sabana Grande','Parroquia',307),
('Cheregüé','Parroquia',307),
('Granados','Parroquia',307),
('Arnoldo Gabaldón','Parroquia',308),
('Bolivia','Parroquia',308),
('Carrillo','Parroquia',308),
('Cegarra','Parroquia',308),
('Chejendé','Parroquia',308),
('Manuel Salvador Ulloa','Parroquia',308),
('San José','Parroquia',308),
('Carache','Parroquia',309),
('La Concepción','Parroquia',309),
('Cuicas','Parroquia',309),
('Panamericana','Parroquia',309),
('Santa Cruz','Parroquia',309),
('Escuque','Parroquia',310),
('La Unión','Parroquia',310),
('Santa Rita','Parroquia',310),
('Sabana Libre','Parroquia',310),
('El Socorro','Parroquia',311),
('Los Caprichos','Parroquia',311),
('Antonio José de Sucre','Parroquia',311),
('Campo Elías','Parroquia',312),
('Arnoldo Gabaldón','Parroquia',312),
('Santa Apolonia','Parroquia',313),
('El Progreso','Parroquia',313),
('La Ceiba','Parroquia',313),
('Tres de Febrero','Parroquia',313),
('El Dividive','Parroquia',314),
('Agua Santa','Parroquia',314),
('Agua Caliente','Parroquia',314),
('El Cenizo','Parroquia',314),
('Valerita','Parroquia',314),
('Monte Carmelo','Parroquia',315),
('Buena Vista','Parroquia',315),
('Santa María del Horcón','Parroquia',315),
('Motatán','Parroquia',316),
('El Baño','Parroquia',316),
('Jalisco','Parroquia',316),
('Pampán','Parroquia',317),
('Flor de Patria','Parroquia',317),
('La Paz','Parroquia',317),
('Santa Ana','Parroquia',317),
('Pampanito','Parroquia',318),
('La Concepción','Parroquia',318),
('Pampanito II','Parroquia',318),
('Betijoque','Parroquia',319),
('José Gregorio Hernández','Parroquia',319),
('La Pueblita','Parroquia',319),
('Los Cedros','Parroquia',319),
('Carvajal','Parroquia',320),
('Campo Alegre','Parroquia',320),
('Antonio Nicolás Briceño','Parroquia',320),
('José Leonardo Suárez','Parroquia',320),
('Sabana de Mendoza','Parroquia',321),
('Junín','Parroquia',321),
('Valmore Rodríguez','Parroquia',321),
('El Paraíso','Parroquia',321),
('Andrés Linares','Parroquia',322),
('Chiquinquirá','Parroquia',322),
('Cristóbal Mendoza','Parroquia',322),
('Cruz Carrillo','Parroquia',322),
('Matriz','Parroquia',322),
('Monseñor Carrillo','Parroquia',322),
('Tres Esquinas','Parroquia',322),
('Cabimbú','Parroquia',323),
('Jajó','Parroquia',323),
('La Mesa de Esnujaque','Parroquia',233),
('Santiago','Parroquia',323),
('Tuñame','Parroquia',323),
('La Quebrada','Parroquia',323),
('Juan Ignacio Montilla','Parroquia',324),
('La Beatriz','Parroquia',324),
('La Puerta','Parroquia',324),
('Mendoza del Valle de Momboy','Parroquia',324),
('Mercedes Díaz','Parroquia',324),
('San Luis','Parroquia',324),
('Caraballeda','Parroquia',325),
('Carayaca','Parroquia',325),
('Carlos Soublette','Parroquia',325),
('Caruao Chuspa','Parroquia',325),
('Catia La Mar','Parroquia',325),
('El Junko','Parroquia',325),
('La Guaira','Parroquia',325),
('Macuto','Parroquia',325),
('Maiquetía','Parroquia',325),
('Naiguatá','Parroquia',325),
('Urimare','Parroquia',325),
('Arístides Bastidas','Parroquia',326),
('Bolívar','Parroquia',327),
('Chivacoa','Parroquia',328),
('Campo Elías','Parroquia',328),
('Cocorote','Parroquia',329),
('Independencia','Parroquia',330),
('José Antonio Páez','Parroquia',331),
('La Trinidad','Parroquia',332),
('Manuel Monge','Parroquia',333),
('Salóm','Parroquia',334),
('Temerla','Parroquia',334),
('Nirgua','Parroquia',334),
('San Andrés','Parroquia',335),
('Yaritagua','Parroquia',335),
('San Javier','Parroquia',336),
('Albarico','Parroquia',336),
('San Felipe','Parroquia',336),
('Sucre','Parroquia',337),
('Urachiche','Parroquia',338),
('El Guayabo','Parroquia',339),
('Farriar','Parroquia',339),
('Isla de Toas','Parroquia',340),
('Monagas','Parroquia',340),
('San Timoteo','Parroquia',341),
('General Urdaneta','Parroquia',341),
('Libertador','Parroquia',341),
('Marcelino Briceño','Parroquia',341),
('Pueblo Nuevo','Parroquia',341),
('Manuel Guanipa Matos','Parroquia',341),
('Ambrosio','Parroquia',342),
('Carmen Herrera','Parroquia',342),
('La Rosa','Parroquia',342),
('Germán Ríos Linares','Parroquia',342),
('San Benito','Parroquia',342),
('Rómulo Betancourt','Parroquia',342),
('Jorge Hernández','Parroquia',342),
('Punta Gorda','Parroquia',342),
('Arístides Calvani','Parroquia',342),
('Encontrados','Parroquia',343),
('Udón Pérez','Parroquia',343),
('Moralito','Parroquia',344),
('San Carlos del Zulia','Parroquia',344),
('Santa Cruz del Zulia','Parroquia',344),
('Santa Bárbara','Parroquia',344),
('Urribarrí','Parroquia',344),
('Carlos Quevedo','Parroquia',345),
('Francisco Javier Pulgar','Parroquia',345),
('Simón Rodríguez','Parroquia',345),
('Guamo-Gavilanes','Parroquia',345),
('La Concepción','Parroquia',347),
('San José','Parroquia',347),
('Mariano Parra León','Parroquia',347),
('José Ramón Yépez','Parroquia',347),
('Jesús María Semprún','Parroquia',348),
('Barí','Parroquia',348),
('Concepción','Parroquia',349),
('Andrés Bello','Parroquia',349),
('Chiquinquirá','Parroquia',349),
('El Carmelo','Parroquia',349),
('Potreritos','Parroquia',349),
('Libertad','Parroquia',350),
('Alonso de Ojeda','Parroquia',350),
('Venezuela','Parroquia',350),
('Eleazar López Contreras','Parroquia',350),
('Campo Lara','Parroquia',350),
('Bartolomé de las Casas','Parroquia',351),
('Libertad','Parroquia',351),
('Río Negro','Parroquia',351),
('San José de Perijá','Parroquia',351),
('San Rafael','Parroquia',352),
('La Sierrita','Parroquia',352),
('Las Parcelas','Parroquia',352),
('Luis de Vicente','Parroquia',352),
('Monseñor Marcos Sergio Godoy','Parroquia',352),
('Ricaurte','Parroquia',352),
('Tamare','Parroquia',352),
('Antonio Borjas Romero','Parroquia',353),
('Bolívar','Parroquia',353),
('Cacique Mara','Parroquia',353),
('Carracciolo Parra Pérez','Parroquia',353),
('Cecilio Acosta','Parroquia',353),
('Cristo de Aranza','Parroquia',353),
('Coquivacoa','Parroquia',353),
('Chiquinquirá','Parroquia',353),
('Francisco Eugenio Bustamante','Parroquia',353),
('Idelfonzo Vásquez','Parroquia',353),
('Juana de Ávila','Parroquia',353),
('Luis Hurtado Higuera','Parroquia',353),
('Manuel Dagnino','Parroquia',353),
('Olegario Villalobos','Parroquia',353),
('Raúl Leoni','Parroquia',353),
('Santa Lucía','Parroquia',353),
('Venancio Pulgar','Parroquia',353),
('San Isidro','Parroquia',353),
('Altagracia','Parroquia',354),
('Faría','Parroquia',354),
('Ana María Campos','Parroquia',354),
('San Antonio','Parroquia',354),
('San José','Parroquia',354),
('Donaldo García','Parroquia',355),
('El Rosario','Parroquia',355),
('Sixto Zambrano','Parroquia',355),
('San Francisco','Parroquia',356),
('El Bajo','Parroquia',356),
('Domitila Flores','Parroquia',356),
('Francisco Ochoa','Parroquia',356),
('Los Cortijos','Parroquia',356),
('Marcial Hernández','Parroquia',356),
('Santa Rita','Parroquia',357),
('El Mene','Parroquia',357),
('Pedro Lucas Urribarrí','Parroquia',357),
('José Cenobio Urribarrí','Parroquia',357),
('Rafael Maria Baralt','Parroquia',358),
('Manuel Manrique','Parroquia',358),
('Rafael Urdaneta','Parroquia',358),
('Bobures','Parroquia',359),
('Gibraltar','Parroquia',359),
('Heras','Parroquia',359),
('Monseñor Arturo Álvarez','Parroquia',359),
('Rómulo Gallegos','Parroquia',359),
('El Batey','Parroquia',359),
('Rafael Urdaneta','Parroquia',360),
('La Victoria','Parroquia',360),
('Raúl Cuenca','Parroquia',360),
('Sinamaica','Parroquia',346),
('Alta Guajira','Parroquia',346),
('Elías Sánchez Rubio','Parroquia',346),
('Guajira','Parroquia',347),
('Altagracia','Parroquia',361),
('Antímano','Parroquia',361),
('Caricuao','Parroquia',361),
('Catedral','Parroquia',361),
('Coche','Parroquia',361),
('El Junquito','Parroquia',361),
('El Paraíso','Parroquia',361),
('El Recreo','Parroquia',361),
('El Valle','Parroquia',361),
('La Candelaria','Parroquia',361),
('La Pastora','Parroquia',361),
('La Vega','Parroquia',361),
('Macarao','Parroquia',361),
('San Agustín','Parroquia',361),
('San Bernardino','Parroquia',361),
('San José','Parroquia',361),
('San Juan','Parroquia',361),
('San Pedro','Parroquia',361),
('Santa Rosalía','Parroquia',361),
('Santa Teresa','Parroquia',361),
('Sucre (Catia)','Parroquia',361),
('23 de enero','Parroquia',361);


Insert into tienda_bd(tien_nombre,tien_tipo,cf_tien_lugar) values

('El Cafetal','Mini Candy Shop',972),
('Maracaibo','Mini Candy Shop',353),
('Barquisimeto','Mini Candy Shop',13),
('El Tigre','Mini Candy Shop',960),
('Guanare','Mini Candy Shop',1087),
('Paraguaná','Mini Candy Shop',11),
('Valle la Pascua','Mini Candy Shop',800),
('Urañe', 'Mini Candy Shop',1223),
('San Félix', 'Mini Candy Shop',745),
('Carora', 'Mini Candy Shop',13),
('Acarigua', 'Mini Candy Shop',18),
('Petare', 'Mini Candy Shop',1009),
('Maracay', 'Mini Candy Shop',5),
('Puerto Ordaz', 'Mini Candy Shop',7),
('San Cristobal', 'Mini Candy Shop',1175),
('Los Teques', 'Mini Candy Shop',986),
('Anaco', 'Mini Candy Shop',387),
('San Casimiro', 'Mini Candy Shop',496),
('San Antonio de los Altos','Mini Candy Shop',996),
('Antimano', 'Mini Candy Shop',1479),
('La Guaira', 'Mini Candy Shop',1345),
('Margarita', 'Mini Candy Shop',17),
('Guanta', 'Mini Candy Shop',401),
('Puerto la Cruz','Mini Candy Shop',411),
('Mérida', 'Mini Candy Shop',14),
('Barinas', 'Mini Candy Shop',530),
('tucacas','Mini Candy Shop',740),
('Costa Oriental del Lago','Mini Candy Shop',1386),
('La Victoria','Mini Candy Shop',1472),
('Villa la Cura','Mini Candy Shop',5),
('Ciudad Ojeda','Mini Candy Shop',24),
('CuidadBolivar','Mini Candy Shop',7),
('Barcelona','Mini Candy Shop',2),
('San Fernando de Apure','Mini Candy Shop',4),
('Valencia', 'Mini Candy Shop',116),
('Maiquetia', 'Mini Candy Shop',1347),
('Carupano', 'Mini Candy Shop',19),
('Coro', 'Mini Candy Shop',2),
('Trujillo','Mini Candy Shop',322);


Insert into rol_bd(rol_nombre,rol_descripcion) values

('Comprador','Persona que compra'),
('Empleado','Tabajador de Candy Ucab'),
('Jefe de Pasillo','Encargado del pasillo'),
('Encargado del Diario','Persona que administra el diario'),
('Gerente','Gerente de la tienda'),
('Recursos Humanos','Encargado de los procesos de recursos humanos'),
('Sub Generente','Asistente del gerente'),
('Administrador','Encargador de la página'),
('Finanzas','Encargado de supervisar los movimientos del capital de Candy Ucab'),
('Evaluador','Encargado de evaluar la pagina');

Insert into permiso_bd(perm_accion) values

('Editar Caramelos'),
('Comprar'),
('Editar Darío'),
('Actualizar valor de puntos'),
('Editar Empleados de Candy Ucab');



Insert into permiso_rol(cf_perm_rol_permiso,cf_perm_rol_rol) values

(1,1),
(2,2),
(3,3),
(4,4),
(5,5);

Insert into tipo_bd(tipo_nombre) values

('Normal'),
('Macizo'),
('Con Chicle'),
('Piruleta'),
('Bombón'),
('Gelatina'),
('Algodón de Azúcar'),
('Con Chocolate'),
('De Fruta'),
('De Regaliz'),
('Sin Azúcar'),
('Picantes'),
('Ácidos'),
('Con colorantes que tinten la lengua');


Insert into producto_bd(prod_nombre, prod_descripcion) values

('Chupetas Rimbombin','Caramelo con palo'),
('Ricolin', 'Caramelo de frutas con vitamina C'),
('Los Firi Firi', 'Tabletas sabor a menta'),
('Chupetas de Corazón','Chupetas con forma de un corazón, con sabor a fresa'),
('Los pirulitos', 'Caramelos blandos'),
('Ricura', 'Bola de caramelo picante'),
('El original', 'Caramelos cítricos'),
('Dulcin', 'Caramelos masticables'),
('Choco Candy', 'Caramelos de Chocolate'),
('Blue', 'Caramelos rellenos');

Insert into producto_tipo(Cf_prod_tipo_producto,cf_prod_tipo_tipo) values
(1,3),
(6,13),
(9,8),
(7,1),
(8,9);

Insert into diario_bd(diar_fechapublicacion,diar_fechafin) values
('2018-05-06', '2018-06-06'),
('2018-07-01', '2018-08-01'),
('2018-03-11', '2018-04-11'),
('2018-07-17', '2018-06-17'),
('2018-01-14', '2018-02-14');

Insert into oferta_bd(ofer_porcentaje, cf_ofer_Prod_tipo,cf_ofer_diario) values
(25,1,1),
(30,2,1),
(45,3,1),
(10,4,1),
(25,5,1),
(50,1,2),
(20,2,2),
(25,3,2),
(35,4,2),
(25,5,2),
(15,1,3),
(05,2,3),
(25,3,3),
(30,4,3),
(35,5,3),
(25,1,4),
(50,2,4),
(05,3,4),
(35,4,4),
(25,5,4),
(05,1,5),
(30,2,5),
(10,3,5),
(25,4,5),
(45,5,5);
